# import numpy

In [2]:
import numpy as np
jeden_wymiar = np.array([1, 2, 3, 4])
type(jeden_wymiar)

numpy.ndarray

# kształt, czyli liczba elementów każdego wymiaru i liczba wymiarów

In [3]:
jeden_wymiar.shape

(4,)

In [4]:
jeden_wymiar.ndim

1

# array poziomy lub pionowy

In [22]:
jeden_wymiar_poziomy = np.array([[1,2,3,4]])
print(jeden_wymiar_poziomy.shape)
jeden_wymiar_poziomy


(1, 4)


array([[1, 2, 3, 4]])

In [23]:
jeden_wymiar_pionowy = jeden_wymiar_poziomy.reshape(-1, 1)
jeden_wymiar_pionowy

array([[1],
       [2],
       [3],
       [4]])

In [24]:
arr_01 = np.array([5, 10, 20])
print(arr_01, arr_01.dtype)
arr_02 = np.array([5, 10, 20.0])
print(arr_02, arr_02.dtype)
arr_03 = np.array([5, 10, '20'])
print(arr_03, arr_03.dtype)

[ 5 10 20] int64
[ 5. 10. 20.] float64
['5' '10' '20'] <U21


In [ ]:
np.linspace(0, 1, 12)[1:-1]   #start, stop, ilosc elementow, slicing bez pierwszego i ostatniego

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

In [60]:
lista = list(range(0, 5))
print(lista)

array = [lista for _ in range(5)]
array

[0, 1, 2, 3, 4]


[[0, 1, 2, 3, 4],
 [0, 1, 2, 3, 4],
 [0, 1, 2, 3, 4],
 [0, 1, 2, 3, 4],
 [0, 1, 2, 3, 4]]

In [ ]:
array = np.array([1,2,0,0,4,0])

indeksy = np.where(array != 0)[0]    #zwraca tyle krotek ile wymiarów, [0] robi slicing i zwraca pierwszą krotkę
print(indeksy)              #zwraca indeksy wartości niezerowych

array_2 = array[array != 0]             #tworzy nowy kopie array i wyciąga z niej wartosci tylko różne od zera

print(array)        
print(array_2)



[0 1 4]
[1 2 0 0 4 0]
[1 2 4]


: 